spring:
  application:
    name: receipt-splitter
  datasource:
    url: jdbc:postgresql://localhost:5432/receipt_splitter
    username: receipt_splitter
    password: receipt_splitter
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        type:
          preferred_instant_jdbc_type: TIMESTAMP_UTC

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: test
